obj-y := report.o func_call_monitor.o ring_buffer.o race_pairs.o race_pairs_monitor.o tracker.o wp_checker.o core.o

ccflags-y += -g -Og -Wno-missing-prototypes -Wno-unused-variable -Wno-unused-function
