# obj-y := delay_checker.o report.o
# obj-y := checker_monitor.o
obj-y := delay_checker.o

ccflags-y += -g -Og -Wno-missing-prototypes -Wno-unused-variable -Wno-unused-function

# CC := /home/zzzccc/llvm-15/llvm-project/build/bin/clang-15
# KERNELDIR ?= /home/zzzccc/linux-6.11
# PWD := $(shell pwd)

# default:
# 	$(MAKE) CC=$(CC) -C $(KERNELDIR) M=$(PWD) modules -w
# clean:
# 	$(MAKE) CC=$(CC) -C $(KERNELDIR) M=$(PWD) clean
